# https://dart.dev/tools/pub/pubspec

name: vagoflax
description: "App for HES-SO students to find a job easily."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.1
  firebase_ui_auth: ^3.1.0
  go_router: ^18.0.0
  image_picker: ^1.2.3
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  url_launcher: ^6.3.2
  http: ^1.6.0
  flutter_litert: ^3.8.0
  google_mlkit_face_detection: ^0.15.1
  tflite_flutter: ^0.12.1
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"      # 1024x1024
  android: true
  ios: true
  remove_alpha_ios: true                   # iOS interdit la transparence
  adaptive_icon_background: "#FFFFFF"      # ou "assets/icon/bg.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/icon.png
    - assets/model/mobile_face_net.tflite
    - assets/ml/model.tflite
    - assets/ml/preprocessing.json
    
dependency_overrides:
  app_links: ^6.3.3
