// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVn4pJjkh7_mVEOliku0_m_Ow1_DPbFGQ',
    appId: '1:133342804424:web:fa9a03b6978d65eb2b68fd',
    messagingSenderId: '133342804424',
    projectId: 'vagoflax-190f6',
    authDomain: 'vagoflax-190f6.firebaseapp.com',
    storageBucket: 'vagoflax-190f6.firebasestorage.app',
    measurementId: 'G-TPXZYVJPPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAClMipwnJ5W9iwmOK_9ltuJ_OWOVRfNOY',
    appId: '1:133342804424:android:b7c877b1e83adc542b68fd',
    messagingSenderId: '133342804424',
    projectId: 'vagoflax-190f6',
    storageBucket: 'vagoflax-190f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZfj20Aw01cB_lSVssFzQT1GuVwfJZII',
    appId: '1:133342804424:ios:5327a292dfb7baeb2b68fd',
    messagingSenderId: '133342804424',
    projectId: 'vagoflax-190f6',
    storageBucket: 'vagoflax-190f6.firebasestorage.app',
    iosBundleId: 'ch.hevs.vagoflax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYZfj20Aw01cB_lSVssFzQT1GuVwfJZII',
    appId: '1:133342804424:ios:5327a292dfb7baeb2b68fd',
    messagingSenderId: '133342804424',
    projectId: 'vagoflax-190f6',
    storageBucket: 'vagoflax-190f6.firebasestorage.app',
    iosBundleId: 'ch.hevs.vagoflax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVn4pJjkh7_mVEOliku0_m_Ow1_DPbFGQ',
    appId: '1:133342804424:web:fa9a03b6978d65eb2b68fd',
    messagingSenderId: '133342804424',
    projectId: 'vagoflax-190f6',
    authDomain: 'vagoflax-190f6.firebaseapp.com',
    storageBucket: 'vagoflax-190f6.firebasestorage.app',
    measurementId: 'G-TPXZYVJPPY',
  );
}
